apiVersion: v1
kind: Service
metadata:
  name: rusty-sonar
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: rusty-sonar
  ports:
    - name: http
      port: 8080
      targetPort: 3000
      protocol: TCP
