apiVersion: v1
kind: Service
metadata:
  name: rusty-sonar
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8080'
spec:
  selector:
    app: rusty-sonar
  ports:
    - name: http
      port: 8080
      targetPort: 8080
